name: threatwinds_sdk
description: ThreatWinds SDK for Dark
version: 1.0.0-dev
repository: https://github.com/threatwinds/dart-sdk

environment:
  sdk: ^3.3.3

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.21.0
dependencies:
  http: ^1.1.0
  json_annotation: ^4.8.1
